version: "2"
services:
  odoo:
    image: odoo:17
    ports:
      - "8069:8069"
      - "8072:8072"
    tty: true
    command: odoo
    depends_on:
      - db
    volumes:
      - data:/var/lib/odoo
      - ./custom_modules:/mnt/extra-addons
      - ./etc:/etc/odoo
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
  db:
    image: postgres:14-alpine
    command: postgres -c 'max_connections=300'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
volumes:
  data:
  postgresql:
# services:
#   odoo:
#     image: odoo:17
#     ports:
#       - "8069:8069"
#       - "8072:8072"
#     tty: true
#     command: odoo -c /etc/odoo/odoo.conf
#     depends_on:
#       - db
#     volumes:
#       - data:/var/lib/odoo
#       - ./custom_modules:/mnt/extra-addons
#       - ./etc:/etc/odoo
#     environment:
#       - HOST=db
#       - USER=odoo
#       - PASSWORD=odoo
#       - POSTGRES_DB=odoo # Ensure this matches the Odoo database name
#     networks:
#       - odoo_network
#   db:
#     image: postgres:14-alpine
#     command: postgres -c 'max_connections=300'
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_PASSWORD=odoo
#       - POSTGRES_USER=odoo
#       - POSTGRES_DB=odoo # Changed from "postgres" to "odoo"
#     volumes:
#       - postgresql:/var/lib/postgresql/data
#     networks:
#       - odoo_network
# volumes:
#   data:
#   postgresql:
# networks:
#   odoo_network:
#     driver: bridge
